name: CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
          cd web/view
          npm ci
          CI=false npm run build
          npm test

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    
    - name: Install go dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    - name: Build
      run: go build -o ./cmd/main
      
    - name: Run vet & lint
      run: |
        go vet .
        golint .
    
    - name: Run backend testing
      run: go test -v
    
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_BACKEND}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_FRONTEND}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "web/view"
          # procfile: "web: cmd/main"